// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdGvSkERuE27uhzzoDoHoZkjR74Xy6kbk',
    appId: '1:821517384462:web:75312cb5ae68d44bbe755f',
    messagingSenderId: '821517384462',
    projectId: 'task-manager-app-85d44',
    authDomain: 'task-manager-app-85d44.firebaseapp.com',
    storageBucket: 'task-manager-app-85d44.firebasestorage.app',
    measurementId: 'G-HXE3KQ1NK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtOn6hZZ-aAUusbwWItSTMo6uoauo2NBY',
    appId: '1:821517384462:android:1b7cd2c2f5e179dabe755f',
    messagingSenderId: '821517384462',
    projectId: 'task-manager-app-85d44',
    storageBucket: 'task-manager-app-85d44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANCgbSEEWzg-JAQlgjeiMWsnL1pfdma4Q',
    appId: '1:821517384462:ios:d287c2512cc9f7abbe755f',
    messagingSenderId: '821517384462',
    projectId: 'task-manager-app-85d44',
    storageBucket: 'task-manager-app-85d44.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceAppOstad',
  );
}
